"""
Create motors table
"""

from yoyo import step

__depends__ = {}

steps = [
    step(
        """
        CREATE TABLE motors (
            id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            location    varchar(255),
            ip  varchar(40) NOT NULL,
            port    integer,
            status  varchar(40),
            statusDate  timestamp
        );
        """
    )
]
